{% set name = "turtleFSI" %}
{% set version = "2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KVSLab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 91ff182e0fa59632e3489acba28297071bfa1a537fcc32f58684d949007d2999

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3
    - setuptools
    - pip

  run:
    - python >=3
    - fenics
    - numpy
    - pyyaml
    - configargparse
    - scipy

test:
  imports:
    - turtleFSI
  source_files:
    - tests/*
  requires:
    - pytest
  commands:
    - pytest ./tests/

about:
  summary: A monolithic fluid structure interaction solver based on FEniCS.
  description: |
    TurtleFSI is a monolithic fluid structure intreaction solver, solving for
    Navier-Stokes in the fluid, and hyperelasticity in the solid. TurtleFSI
    benefits from the HPC capabilities in FEniCS.
  home: https://turtlefsi2.readthedocs.io/en/latest/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://turtlefsi2.readthedocs.io/en/latest/
  dev_url: https://github.com/KVSLab/turtleFSI

extra:
  recipe-maintainers:
    - keiyamamo
    - aslakbergersen
    - albansouche
